spring:
  jpa:
    hibernate:
      ddl-auto: none

starwarsapi:
  url: https://swapi.dev/api/
  resources:
    characters: ${starwarsapi.url}people/
    planets: ${starwarsapi.url}planets/
    starships: ${starwarsapi.url}starships/
  cron: 0 0 0/1 * * *

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
